# Generated by Django 2.2.12 on 2020-07-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=8, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('disability', models.CharField(blank=True, max_length=50, null=True)),
                ('muslim_minority', models.BooleanField(default=False, verbose_name='Muslim Minority')),
                ('other_minority', models.CharField(blank=True, choices=[('christian', 'Christians'), ('sikh', 'Sikhs'), ('buddhists', 'Bhuddhists'), ('zoroastrians', 'Zoroastrians'), ('jain', 'Jains')], max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('maratial_status', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(max_length=20, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhar', models.IntegerField(blank=True, null=True)),
                ('program', models.CharField(max_length=20, null=True)),
                ('year_of_study', models.CharField(max_length=10, null=True)),
                ('mother_name', models.CharField(max_length=20, null=True)),
                ('father_name', models.CharField(max_length=20, null=True)),
                ('parent_email', models.CharField(max_length=20, null=True)),
                ('parent_contact', models.IntegerField(null=True)),
                ('local_guardian', models.CharField(max_length=20, null=True)),
                ('emergency_number', models.IntegerField(null=True)),
                ('education_load', models.BooleanField(default=False, verbose_name='Education loan availed')),
                ('scholarship', models.BooleanField(default=False, verbose_name='Scholarship availed')),
                ('last_year_amount', models.IntegerField(null=True)),
                ('last_year_payment_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('last_year_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_year_date', models.CharField(blank=True, max_length=10, null=True)),
                ('current_year_amount_transferred', models.IntegerField(null=True)),
                ('current_year_payment_mode', models.CharField(blank=True, max_length=10, null=True)),
                ('current_year_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('current_year_date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
