# Generated by Django 2.2.12 on 2020-07-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_form',
            name='education_load',
        ),
        migrations.AddField(
            model_name='data_form',
            name='education_loan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_form',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data_form',
            name='dob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='data_form',
            name='emergency_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_form',
            name='muslim_minority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='data_form',
            name='other_minority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data_form',
            name='parent_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data_form',
            name='scholarship',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
