# Generated by Django 2.2.12 on 2020-07-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200716_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_form',
            name='current_year_transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_form',
            name='last_year_transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
