# Generated by Django 2.2.12 on 2020-07-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200716_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_form',
            name='anti_ragging',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='data_form',
            name='photograph',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='data_form',
            name='readmission_fee_undertaking',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='data_form',
            name='readmisson_acceptance_form',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
