# Generated by Django 2.2.12 on 2020-07-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200717_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_form',
            name='semister',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='urn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
