# Generated by Django 2.2.12 on 2020-07-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20200717_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_form',
            old_name='adress',
            new_name='address',
        ),
    ]
