# Generated by Django 2.2.12 on 2020-07-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20200718_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_form',
            name='muslim_minority',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
