# Generated by Django 3.0 on 2021-02-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20200721_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_form',
            old_name='middle_name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='data_form',
            name='father_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='padress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='pcity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='pcountry',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='ppin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='pstate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
