# Generated by Django 3.0 on 2021-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20210202_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_form',
            old_name='other_minority',
            new_name='award_name1',
        ),
        migrations.RenameField(
            model_name='data_form',
            old_name='disability',
            new_name='choice',
        ),
        migrations.RenameField(
            model_name='data_form',
            old_name='current_year_transaction_id',
            new_name='remark2',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='anti_ragging',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='current_year_amount_transferred',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='current_year_date',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='current_year_payment_mode',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='education_loan',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='emergency_number',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='last_year_amount',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='last_year_date',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='last_year_payment_mode',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='last_year_transaction_id',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='local_guardian',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='muslim_minority',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='parent_contact',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='program',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='readmission_fee_undertaking',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='readmisson_acceptance_form',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='semister',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='urn',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='data_form',
            name='award_name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='board1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='board2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='cgpa1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='cgpa2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='cgpa3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='cgpa4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='college1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='college2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='college3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='college4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='des1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='des2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='from1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='from2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='gf1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='gf2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='gf3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='gf4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='gt1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='gt2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='gt3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='gt4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='institute1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='institute2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='level1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='level2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='marks1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='marks2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='max_marks1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='max_marks2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mmarks1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mmarks2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mmarks3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mmarks4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mo1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mo2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mo3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='mo4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='name_of_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='nature_work1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='nature_work2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='nos1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='nos2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='org_name1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='org_name2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='percent1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='percent2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='pob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='remark1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='salary1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='salary2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='secondary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='sfrom1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='sfrom2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='sr_secondary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='sto1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='sto2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='to1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='to2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='total_exp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='uni1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='uni2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='uni3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='uni4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='why_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='year1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='year2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='yr1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='yr2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='yr3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_form',
            name='yr4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
