# Generated by Django 3.0 on 2021-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_auto_20210204_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_form',
            name='cgpa2',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='cgpa3',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='cgpa4',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='college2',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='college3',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='college4',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='graduation_year2',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='graduation_year3',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='graduation_year4',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mmarks2',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mmarks3',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mmarks4',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mo2',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mo3',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mo4',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='photograph',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='uni2',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='uni3',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='uni4',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='why_study',
        ),
    ]
