# Generated by Django 3.0 on 2021-02-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20210208_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_form',
            name='fater_education',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='father_income',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mother_education',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mother_income',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='mother_occupation',
        ),
    ]
