# Generated by Django 3.0 on 2021-02-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20210208_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_form',
            name='course',
        ),
        migrations.RemoveField(
            model_name='data_form',
            name='why_study',
        ),
    ]
