from django.db import models

# Create your models here.
class data_form(models.Model):
    first_name = models.CharField(null=True, blank=True, max_length=50)
    middle_name = models.CharField(null=True, blank=True, max_length=50)
    last_name = models.CharField(null=True, blank=True, max_length=50)
    dob = models.CharField(null=True, blank=True, max_length=15)
    contact = models.CharField(null=True, blank=False, max_length=20)
    blood_group = models.CharField(null=True, blank=True, max_length=10)
    gender = models.CharField(null=True, blank=True, max_length=10)
    disability = models.CharField(null=True, blank=True, max_length=50)
    muslim_minority = models.CharField(null=True, blank=True, max_length=10)
    other_minority = models.CharField(null=True, blank=True, max_length=100)
    category = models.CharField(null=True, blank=True, max_length=50)
    maratial_status = models.CharField(null=True, blank=True, max_length=20)
    nationality = models.CharField(null=True, blank=False, max_length=20)
    adress = models.TextField(null=True, blank=True)
    city = models.CharField(null=True, blank=True, max_length=50)
    state = models.CharField(null=True, blank=True, max_length=50)
    aadhar = models.IntegerField(null=True, blank= True)
    program = models.CharField(null=True, blank=False, max_length=50)
    year_of_study = models.CharField(null=True, blank=False, max_length=10)
    mother_name = models.CharField(null=True, blank=False, max_length=20)
    father_name = models.CharField(null=True, blank=False, max_length=20)
    parent_email = models.CharField(null=True, blank=False, max_length=20)
    parent_contact = models.CharField(null=True, blank=False, max_length=20)
    local_guardian = models.CharField(null=True, blank=False, max_length=20)
    degree = models.CharField(null=True, blank=True, max_length=10)
    semister = models.CharField(null=True, blank=True, max_length=10)
    urn = models.CharField(null=True, blank=True,max_length=20)
    emergency_number = models.CharField(null=True, blank=False, max_length=50)
    education_loan = models.CharField(null=True, blank=False, max_length=50)
    scholarship = models.CharField(null=True, blank=False, max_length=50)
    last_year_amount = models.IntegerField(null=True, blank=False)
    last_year_payment_mode = models.CharField(null=True, blank=True, max_length=10)
    last_year_transaction_id = models.TextField(null=True, blank=True)
    last_year_date = models.CharField(null=True, blank=True, max_length=10)
    current_year_amount_transferred = models.IntegerField(null=True, blank=False)
    current_year_payment_mode = models.CharField(null=True, blank=True, max_length=10)
    current_year_transaction_id = models.TextField(null=True, blank=True)
    current_year_date = models.CharField(null=True, blank=True, max_length=10)
    anti_ragging = models.FileField(null=True, blank=True)
    readmission_fee_undertaking = models.FileField(null=True, blank=True)
    readmisson_acceptance_form = models.FileField(null=True, blank=True)
    photograph = models.FileField(null=True, blank=True)

    def __str__(self):
        return self.first_name + " " + self.last_name